
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.analizadores;

/** CUP generated class containing symbol constants. */
public class sym1 {
  /* terminals */
  public static final int RArr = 12;
  public static final int RGra = 15;
  public static final int com = 2;
  public static final int Parc = 4;
  public static final int numerico = 16;
  public static final int RMre = 8;
  public static final int Para = 3;
  public static final int RAba = 13;
  public static final int RAtr = 11;
  public static final int EOF = 0;
  public static final int RFin = 6;
  public static final int RAde = 10;
  public static final int Rcm = 14;
  public static final int RIni = 5;
  public static final int error = 1;
  public static final int RMdi = 9;
  public static final int RTra = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "com",
  "Para",
  "Parc",
  "RIni",
  "RFin",
  "RTra",
  "RMre",
  "RMdi",
  "RAde",
  "RAtr",
  "RArr",
  "RAba",
  "Rcm",
  "RGra",
  "numerico"
  };
}

