/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnz.frontend;

import gnz.analizadores.Lexico;
import gnz.analizadores.parser;
import gnz.backend.Matriz.ManejadorMatriz;
import gnz.backend.Matriz.Run;
import gnz.backend.archivos.ManejadorDeArchivos;
import gnz.backend.objetoMovil.Archivos;
import gnz.backend.objetoMovil.Coordenada;
import gnz.backend.objetoMovil.Movil;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.StringReader;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jesfrin
 */
public class FrameOM extends javax.swing.JFrame {

    //VARIABLES NECESARIAS
    Movil movil = new Movil(this);
    JFileChooser seleccionar = new JFileChooser();
    File Archivo;
    FileOutputStream salida;
    //Variables para mapa
    private ManejadorDePanel manPanel;
    private ManejadorDeArchivos manArchivos;

    /**
     * Creates new form LaberintoFrame
     */
    public FrameOM() {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Objeto Movil");
        //Elementos para creacion de mapa
        this.manPanel = new ManejadorDePanel(this, 50);
        actualizarEquivalencia();
        this.manArchivos = new ManejadorDeArchivos(this);
        //Elementos para movimieto libre del objeto movil
        movil.getObjetoMovil().setIcon(new ImageIcon(getClass().getResource("coche1.png")));
        System.out.println(getClass().getResource(""));
        movil.getObjetoMovil().setSize((26 * Run.MULT), (16 * Run.MULT));
        movil.getObjetoMovil().setVisible(true);
        this.matrizPanel.add(movil.getObjetoMovil(), 0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrizPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        coordenadasjLabel = new javax.swing.JLabel();
        borrarCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cambiarCuadriculajComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        equivalenciajLabel = new javax.swing.JLabel();
        cambiarColorButton = new javax.swing.JButton();
        guardarMapajButton = new javax.swing.JButton();
        abrirMapaButton = new javax.swing.JButton();
        guardarComojButton = new javax.swing.JButton();
        nuevoMapajButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        borrarMapajButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matrizPanel.setBackground(new java.awt.Color(254, 254, 254));
        matrizPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        matrizPanel.setName(""); // NOI18N
        matrizPanel.setPreferredSize(new java.awt.Dimension(601, 601));
        matrizPanel.setRequestFocusEnabled(false);
        matrizPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                matrizPanelMouseDragged(evt);
            }
        });
        matrizPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matrizPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout matrizPanelLayout = new javax.swing.GroupLayout(matrizPanel);
        matrizPanel.setLayout(matrizPanelLayout);
        matrizPanelLayout.setHorizontalGroup(
            matrizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        matrizPanelLayout.setVerticalGroup(
            matrizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        coordenadasjLabel.setText("Coordenadas:");

        borrarCheckBox.setText("Borrar al mantener presionado");

        jLabel1.setText("Cambio de cuadricula");

        cambiarCuadriculajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "30", "50", "100", "150", "200" }));
        cambiarCuadriculajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarCuadriculajComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Equivalencia:");

        equivalenciajLabel.setText("cm");

        cambiarColorButton.setText("Cambiar color");
        cambiarColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarColorButtonActionPerformed(evt);
            }
        });

        guardarMapajButton.setText("Guardar mapa");
        guardarMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMapajButtonActionPerformed(evt);
            }
        });

        abrirMapaButton.setText("Abrir mapa");
        abrirMapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMapaButtonActionPerformed(evt);
            }
        });

        guardarComojButton.setText("Guardar como");
        guardarComojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComojButtonActionPerformed(evt);
            }
        });

        nuevoMapajButton.setText("Nuevo mapa");
        nuevoMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMapajButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar puerto");

        jButton2.setText("Log");

        borrarMapajButton.setText("Borrar todo");
        borrarMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMapajButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(130, 226, 33));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cambiarCuadriculajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(borrarCheckBox)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coordenadasjLabel)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(equivalenciajLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guardarComojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(abrirMapaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cambiarColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrarMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coordenadasjLabel)
                .addGap(18, 18, 18)
                .addComponent(borrarCheckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cambiarCuadriculajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equivalenciajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarMapajButton)
                    .addComponent(cambiarColorButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirMapaButton)
                    .addComponent(nuevoMapajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarComojButton)
                    .addComponent(guardarMapajButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mapa", jPanel3);

        jLabel3.setText("COMANDOS");

        jLabel4.setText("MOVIMIENTO=N, R; ANGULO=GRADOS; DISTANCIA=CENTIMETROS");

        jButton3.setText("ABRIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("CORDENADA X");

        jLabel6.setText("CORDENADA Y");

        jButton4.setText("EJECUTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");

        jButton5.setText("POSICIONAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(15, 216, 49));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel7.setText("0");

        jLabel8.setBackground(new java.awt.Color(15, 216, 49));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setText("0");

        jButton6.setText("POINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("OBSTACULO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel9.setText("MOVIMIENTOS QUE SE REALIZARAN");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton8.setText("GUARDAR HISTORICO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("LIMPIAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(43, 43, 43)
                                            .addComponent(jLabel6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(227, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(71, 71, 71))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addContainerGap(646, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Movimiento Libre", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matrizPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(matrizPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matrizPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matrizPanelMouseClicked
        this.manArchivos.setMapaEstaGuardado(false);
        this.manPanel.accionParaClick(evt);
    }//GEN-LAST:event_matrizPanelMouseClicked

    private void matrizPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matrizPanelMouseDragged
        this.manArchivos.setMapaEstaGuardado(false);
        this.manPanel.accionParaMouseDragged(evt);
    }//GEN-LAST:event_matrizPanelMouseDragged

    private void borrarMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMapajButtonActionPerformed
        this.matrizPanel.setBackground(Color.BLACK);
        this.matrizPanel.setBackground(Color.WHITE);
    }//GEN-LAST:event_borrarMapajButtonActionPerformed

    private void nuevoMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMapajButtonActionPerformed
        try {
            this.manArchivos.crearNuevoMapa(this.manPanel.getManMatriz(), this.matrizPanel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Mo se pudo crear un nuevo mapa");
            Logger.getLogger(FrameOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nuevoMapajButtonActionPerformed

    private void guardarComojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComojButtonActionPerformed
        try {
            this.manArchivos.guardarMapaComo(this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el mapa");
            Logger.getLogger(FrameOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarComojButtonActionPerformed

    private void abrirMapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMapaButtonActionPerformed
        try {
            this.manArchivos.abrirMapa(this.matrizPanel, this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Por favor de click en el panel antes de abrir el archivo");
            Logger.getLogger(FrameOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirMapaButtonActionPerformed

    private void guardarMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMapajButtonActionPerformed
        try {
            this.manArchivos.guardarMapaEnArchivo(this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el mapa");
            Logger.getLogger(FrameOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarMapajButtonActionPerformed

    private void cambiarColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = colorChooser.showDialog(null, "Seleccione un color", this.manPanel.getColor());
        this.manPanel.setColor(color);
    }//GEN-LAST:event_cambiarColorButtonActionPerformed

    private void cambiarCuadriculajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarCuadriculajComboBoxActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Se borrara el mapa actual");
        System.out.println("OPCION:" + opcion);
        switch (opcion) {
            case 0:
                this.matrizPanel.setBackground(Color.BLACK);
                this.matrizPanel.setBackground(Color.WHITE);
                this.manPanel = new ManejadorDePanel(this, Integer.valueOf(String.valueOf(this.cambiarCuadriculajComboBox.getSelectedItem())));
                JOptionPane.showMessageDialog(this, "Cuadricula cambiada");
                actualizarEquivalencia();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cambiarCuadriculajComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //ABRIR EL ARCHIVO
        jTextArea1.setText("");
        Archivos arc = new Archivos();
        File f = arc.Abrir();
        if (f != null) {
            jTextArea1.setText(arc.leer(f.toString()));
        } else {
            JOptionPane.showMessageDialog(null, "NO SE SELECCIONO NINGUN FICHERO");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //LO QUE ESTA COMENTADO ES SOLO PARA ESCRIBIR UN NOMBRE DEL GRUPO PARA IMPRIMIRLO POR EL JTEXTAREA
        //String grupo= JOptionPane.showInputDialog("ESCRIBA EL NOMBRE DE SU EQUIPO");
        //if(grupo!=null){
        //  if(!grupo.equals("")){
        //jTextArea2.append("--------------------------NOMBRE DEL GRUPO: "+grupo+"--------------------------\n");
        if (!jTextArea1.getText().equals("")) {

            Lexico lexico = new Lexico(new BufferedReader(new StringReader(jTextArea1.getText())));
            parser sin1 = new parser(lexico);
            try {
                sin1.parse();
            } catch (Exception e) {
            }
            movil.limpiar();
            if (sin1.listavalores != null) {
                movil.enviar(sin1.listavalores, 30, jLabel7, jLabel8, jTextArea2);
            } else {
                JOptionPane.showMessageDialog(null, "EXISTEN ERRORES EN SU ARCHIVO INTENTE DE NUEVO");
            }
            //jTextArea2.setText(sin1.csv.movimientos(objeto.objetoMovil.getX(), objeto.objetoMovil.getY()));
        } else {
            JOptionPane.showMessageDialog(null, "PRIMERO ESCRIBA ALGUN COMANDO");
        }
        //}else{
        //  JOptionPane.showMessageDialog(null, "ANTES DE EJECUTAR COLOQUE EL NOMBRE DE SU GRUPO");
        //}
        //}else{
        //  JOptionPane.showMessageDialog(null, "ANTES DE EJECUTAR COLOQUE EL NOMBRE DE SU GRUPO");
        //}
        this.manPanel.dibujarCuadriculaDeMatriz(this.manPanel.getManMatriz(), matrizPanel);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ((!jTextField1.getText().equals("")) && (!jTextField2.getText().equals(""))) {
            int cordenadax = (Integer.parseInt(jTextField1.getText()) * Run.MULT);
            int cordenaday = (Integer.parseInt(jTextField2.getText()) * Run.MULT);
            movil.repos(cordenadax, cordenaday, jTextArea2);
            movil.limpiar();
                    this.manPanel.dibujarCuadriculaDeMatriz(this.manPanel.getManMatriz(), matrizPanel);


        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jLabel7.setText("" + movil.getObjetoMovil().getX() / Run.MULT);
        jLabel8.setText("" + (movil.getObjetoMovil().getY()) / Run.MULT);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if ((!jTextField1.getText().equals("")) && (!jTextField2.getText().equals(""))) {
            int cordenadax = (Integer.parseInt(jTextField1.getText()));
            int cordenaday = (Integer.parseInt(jTextField2.getText()));
            movil.limpiar();
            movil.coordenadas.add(new Coordenada(cordenadax, cordenaday));
            jTextField1.setText("");
            jTextField2.setText("");
            JOptionPane.showMessageDialog(null, "SE AGREGO EL OBSTACULO");

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (seleccionar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            Archivo = seleccionar.getSelectedFile();
            String Documento = jTextArea2.getText();
            String mensaje = guardar(Archivo, Documento);
            if (mensaje != null) {
                JOptionPane.showMessageDialog(null, mensaje);
            } else {
                JOptionPane.showMessageDialog(null, "Extencion no comaptible");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextArea2.setText("");

    }//GEN-LAST:event_jButton9ActionPerformed

    public String guardar(File Archivo, String documento) {
        String mensaje = null;
        try {
            salida = new FileOutputStream(Archivo);
            byte[] bytext = documento.getBytes();
            salida.write(bytext);
            mensaje = "Se guardo el proyecto";
        } catch (Exception e) {
        }
        return mensaje;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirMapaButton;
    private javax.swing.JCheckBox borrarCheckBox;
    private javax.swing.JButton borrarMapajButton;
    private javax.swing.JButton cambiarColorButton;
    private javax.swing.JComboBox<String> cambiarCuadriculajComboBox;
    private javax.swing.JLabel coordenadasjLabel;
    private javax.swing.JLabel equivalenciajLabel;
    private javax.swing.JButton guardarComojButton;
    private javax.swing.JButton guardarMapajButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel matrizPanel;
    private javax.swing.JButton nuevoMapajButton;
    // End of variables declaration//GEN-END:variables

    public void cambiarTextoDeCoordenadas(String texto) {
        this.coordenadasjLabel.setText(texto);
    }

    public boolean seDebeBorrarAlMantenerPresionado() {
        return borrarCheckBox.isSelected();
    }

    public void actualizarEquivalencia() {
        jLabel2.setText("Equivalencia para " + this.manPanel.getNumeroDeCuadros() + " cuadros:");
        DecimalFormat df = new DecimalFormat("#");
        this.equivalenciajLabel.setText(df.format(ManejadorMatriz.LONGITUD_REALCM / this.manPanel.getNumeroDeCuadros()) + " cm");
    }

    public ManejadorDePanel getManPanel() {
        return manPanel;
    }

    public void setManPanel(ManejadorDePanel manPanel) {
        this.manPanel = manPanel;
    }

    public JPanel getMatrizPanel() {
        return matrizPanel;
    }

}
