/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnz.frontend;

import gnz.backend.Matriz.ManejadorMatriz;
import gnz.backend.archivos.ManejadorDeArchivos;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jesfrin
 */
public class LaberintoFrame extends javax.swing.JFrame {

    private ManejadorDePanel manPanel;
    private ManejadorDeArchivos manArchivos;

    /**
     * Creates new form LaberintoFrame
     */
    public LaberintoFrame() {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Creacion de Mapas");
        this.manPanel = new ManejadorDePanel(this, 50);
        actualizarEquivalencia();
        this.manArchivos = new ManejadorDeArchivos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrizPanel = new javax.swing.JPanel();
        cambiarColorButton = new javax.swing.JButton();
        coordenadasjLabel = new javax.swing.JLabel();
        borrarCheckBox = new javax.swing.JCheckBox();
        cambiarCuadriculajComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        borrarMapajButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        equivalenciajLabel = new javax.swing.JLabel();
        guardarMapajButton = new javax.swing.JButton();
        abrirMapaButton = new javax.swing.JButton();
        guardarComojButton = new javax.swing.JButton();
        nuevoMapajButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        matrizPanel.setBackground(new java.awt.Color(254, 254, 254));
        matrizPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        matrizPanel.setName(""); // NOI18N
        matrizPanel.setPreferredSize(new java.awt.Dimension(601, 601));
        matrizPanel.setRequestFocusEnabled(false);
        matrizPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                matrizPanelMouseDragged(evt);
            }
        });
        matrizPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matrizPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout matrizPanelLayout = new javax.swing.GroupLayout(matrizPanel);
        matrizPanel.setLayout(matrizPanelLayout);
        matrizPanelLayout.setHorizontalGroup(
            matrizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        matrizPanelLayout.setVerticalGroup(
            matrizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        cambiarColorButton.setText("Cambiar color");
        cambiarColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarColorButtonActionPerformed(evt);
            }
        });

        coordenadasjLabel.setText("Coordenadas:");

        borrarCheckBox.setText("Borrar al mantener presionado");

        cambiarCuadriculajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "30", "50", "100", "150", "200" }));
        cambiarCuadriculajComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarCuadriculajComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Cambio de cuadricula");

        borrarMapajButton.setText("Borrar todo");
        borrarMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMapajButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Equivalencia");

        jPanel2.setBackground(new java.awt.Color(130, 226, 33));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        equivalenciajLabel.setText("cm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(equivalenciajLabel)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equivalenciajLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        guardarMapajButton.setText("Guardar mapa");
        guardarMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMapajButtonActionPerformed(evt);
            }
        });

        abrirMapaButton.setText("Abrir mapa");
        abrirMapaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMapaButtonActionPerformed(evt);
            }
        });

        guardarComojButton.setText("Guardar como");
        guardarComojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarComojButtonActionPerformed(evt);
            }
        });

        nuevoMapajButton.setText("Nuevo mapa");
        nuevoMapajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMapajButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar puerto");

        jButton2.setText("Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matrizPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordenadasjLabel)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarCheckBox)
                    .addComponent(jLabel1)
                    .addComponent(cambiarCuadriculajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(guardarComojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abrirMapaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cambiarColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrarMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nuevoMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardarMapajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(matrizPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(coordenadasjLabel)
                .addGap(42, 42, 42)
                .addComponent(borrarCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarColorButton)
                    .addComponent(borrarMapajButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirMapaButton)
                    .addComponent(nuevoMapajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarComojButton)
                    .addComponent(guardarMapajButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiarCuadriculajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matrizPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matrizPanelMouseClicked
        this.manArchivos.setMapaEstaGuardado(false);
        this.manPanel.accionParaClick(evt);
    }//GEN-LAST:event_matrizPanelMouseClicked

    private void matrizPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matrizPanelMouseDragged
        this.manArchivos.setMapaEstaGuardado(false);
        this.manPanel.accionParaMouseDragged(evt);
    }//GEN-LAST:event_matrizPanelMouseDragged

    private void cambiarColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarColorButtonActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        Color color = colorChooser.showDialog(null, "Seleccione un color", this.manPanel.getColor());
        this.manPanel.setColor(color);
    }//GEN-LAST:event_cambiarColorButtonActionPerformed

    private void cambiarCuadriculajComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarCuadriculajComboBoxActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Se borrara el mapa actual");
        System.out.println("OPCION:" + opcion);
        switch (opcion) {
            case 0:
                this.matrizPanel.setBackground(Color.BLACK);
                this.matrizPanel.setBackground(Color.WHITE);
                this.manPanel = new ManejadorDePanel(this, Integer.valueOf(String.valueOf(this.cambiarCuadriculajComboBox.getSelectedItem())));
                JOptionPane.showMessageDialog(this, "Cuadricula cambiada");
                actualizarEquivalencia();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cambiarCuadriculajComboBoxActionPerformed

    private void borrarMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMapajButtonActionPerformed
        this.matrizPanel.setBackground(Color.BLACK);
        this.matrizPanel.setBackground(Color.WHITE);
    }//GEN-LAST:event_borrarMapajButtonActionPerformed

    private void guardarMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMapajButtonActionPerformed
        try {
            this.manArchivos.guardarMapaEnArchivo(this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el mapa");
            Logger.getLogger(LaberintoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarMapajButtonActionPerformed

    private void abrirMapaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMapaButtonActionPerformed
        try {
            this.manArchivos.abrirMapa(this.matrizPanel, this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Por favor de click en el panel antes de abrir el archivo");
            Logger.getLogger(LaberintoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_abrirMapaButtonActionPerformed

    private void nuevoMapajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMapajButtonActionPerformed
        try {
            this.manArchivos.crearNuevoMapa(this.manPanel.getManMatriz(), this.matrizPanel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Mo se pudo crear un nuevo mapa");
            Logger.getLogger(LaberintoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nuevoMapajButtonActionPerformed

    private void guardarComojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarComojButtonActionPerformed
        try {
            this.manArchivos.guardarMapaComo(this.manPanel.getManMatriz());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar el mapa");
            Logger.getLogger(LaberintoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarComojButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirMapaButton;
    private javax.swing.JCheckBox borrarCheckBox;
    private javax.swing.JButton borrarMapajButton;
    private javax.swing.JButton cambiarColorButton;
    private javax.swing.JComboBox<String> cambiarCuadriculajComboBox;
    private javax.swing.JLabel coordenadasjLabel;
    private javax.swing.JLabel equivalenciajLabel;
    private javax.swing.JButton guardarComojButton;
    private javax.swing.JButton guardarMapajButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel matrizPanel;
    private javax.swing.JButton nuevoMapajButton;
    // End of variables declaration//GEN-END:variables

    public void cambiarTextoDeCoordenadas(String texto) {
        this.coordenadasjLabel.setText(texto);
    }

    public boolean seDebeBorrarAlMantenerPresionado() {
        return borrarCheckBox.isSelected();
    }

    public void actualizarEquivalencia() {
        jLabel2.setText("Equivalencia para " + this.manPanel.getNumeroDeCuadros() + " cuadros:");
        DecimalFormat df = new DecimalFormat("#");
        this.equivalenciajLabel.setText(df.format(ManejadorMatriz.LONGITUD_REALCM / this.manPanel.getNumeroDeCuadros()) + " cm");
    }

    public ManejadorDePanel getManPanel() {
        return manPanel;
    }

    public void setManPanel(ManejadorDePanel manPanel) {
        this.manPanel = manPanel;
    }

}
